# Generated by Django 5.1.6 on 2025-02-18 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_result_passed_alter_result_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, default=None, help_text='Time limit in seconds for this question. Leave blank to use quiz default.', null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
