# Generated by Django 5.1.6 on 2025-02-18 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, default=60, help_text='Time limit in seconds for this question. Leave blank to use quiz default.', null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
